ComputationalRadiationPhysics/libSplash

- src/include/splash/core/DCHelper.hpp
Red Hat 4.4.7-3 + GCC 4.4.7
(Scientific Linux 6 on LBL's [Lawrencium](https://sites.google.com/a/lbl.gov/high-performance-computing-services-group/lbnl-supercluster/lawrencium))
`DCHelper.hpp:151: error: call of overloaded 'abs(size_t)' is ambiguous`
`abs(size_t)` lives in `<cstdlib>` (not `<cmath>`) and is not in the `std::` namespace [1]
[1] http://compgroups.net/comp.lang.c++.moderated/std-abs-int-ambiguous/195658
> Fix abs(size_t) Compile Error on Red Hat

- .travis.yml
Non-zero return types of scripts in the `after_script` section do NOT mark the build as failed:
http://docs.travis-ci.com/user/build-lifecycle/
> Travis: Run tests in "script"

- src/DomainCollector.cpp
- src/ParallelDataCollector.cpp
- src/SerialDataCollector.cpp
- src/include/splash/Dimensions.hpp
- src/include/splash/core/DCHelper.hpp
- src/include/splash/domains/DataContainer.hpp
- src/include/splash/sdc_defines.hpp
Reduce magic numbers by using the actual define of `DSP_DIM_MAX` where appropriate.
Even if that does not itself increase flexibility, it should already help reducing the cost if someone wants to generalize the implementation in the future (and: `DSP_DIM_MAX` was basically unused so far).
> Use the define DSP_DIM_MAX instead of 3

- src/DCAttribute.cpp
- src/ParallelDataCollector.cpp
- src/SerialDataCollector.cpp
- src/include/splash/DataCollector.hpp
- src/include/splash/IParallelDataCollector.hpp
- src/include/splash/ParallelDataCollector.hpp
- src/include/splash/SerialDataCollector.hpp
- src/include/splash/core/DCAttribute.hpp
- src/include/splash/version.hpp
- tests/AttributesTest.cpp
- tests/Parallel_AttributesTest.cpp
- tests/include/AttributesTest.h
- tests/readBoolChar.py
Close #170 by implementing additional interfaces to write attributes (global and per iteration) that can be used with simple HDF5 dataspaces.
"Simple Dataspaces" were only used with data sets, e.g., arrays or matrices but are the first choice for actual multi-dimensional array attributes, too (and compatible with `h5py`). Currently, we only supported to use specific types (see #170) that were either `compound` (different types) or `array` (N-times the same) types.
> Close #170 Simple Dataspaces for Attributes

- CMakeLists.txt
- cmake/FindHDF5.cmake
The default `FindHDF5.cmake` module has no VERSION support.
The introduced "requirement" in #169 is without effect for now - this pull request changes that.
An upstream patch was send to: https://github.com/Kitware/CMake/pull/153, now [in review](http://public.kitware.com/pipermail/cmake-developers/2015-May/025225.html) -> [merged](https://github.com/Kitware/CMake/commit/58d6709e64d3ae061da2b9db49ce9d884a77e654)!
Available since 25th of July 2015 in [CMake 3.3.0+](http://www.kitware.com/blog/home/post/940) (but not announced in the blog post ;) )
> CMake: Find HDF5 Version

- doc/Doxyfile
Doxygen: The project name for our `gh-pages` should be `libSplash` and not the old name (`libDataCollector`).
> Doxygen: Project Name libSplash

- CMakeLists.txt
- src/include/splash/version.hpp
~~Pls do not merge this commit before #176~~
~~After the above commit was merged, I will *rebase* this pull request~~
This commit adds support to libSplash to remember the HDF5 version it was build against.
This is interesting, since depending software usually does not include `<hdf5.h>` and can not query the version of HDF5 directly via the includes.
That does not prevent users to compile HDF5 and libSplash both with shared libs and to mix various versions, but the `SPLASH_HDF_VERSION` will still point to the version Splash was originially build (and should be used) with.
> Remember HDF5 Version

- CMakeLists.txt
- src/ParallelDataCollector.cpp
- src/SDCHelper.cpp
- src/include/splash/core/SDCHelper.hpp
- src/include/splash/sdc_defines.hpp
- tests/readBoolChar.py
Closes issue #180: create two string attributes under `/header/` `splashVersion` and `splashFormat` so people know what kind of files they are dealing with.
> Close #180: Write Splash Version & Format

- src/ParallelDataCollector.cpp
- src/include/splash/ParallelDataCollector.hpp
- src/include/splash/pdc_defines.hpp
When writing global attributes in parallel mode, one would expect them to be under the root `/` path (and to be identical for each rank).
This closes #173 and is a requirement to allow implementations to fulfill the openPMD standard.
Serial writes are not affected and still write to `/custom` (each of the ranks). A later refactoring could consider just to let one rank write to `/` here, too (and to ingore the others assuming an actual "global" == identical value).
> Close #173: Parallel Write of Global Attributes

- tests/run_parallel_tests
- tests/run_tests
This pull request adds a test to check if command line arguments are given for `run_tests` and `run_parallel_tests`. If no argument is given a warning is printed and the prevoisly defined default is used.
This closes issue #154. 
@ax3l Please have a look.
> close #154: add warning to test run scripts if no build directory is given

- CMakeLists.txt
This PR refactores the CMakeLists.txt a little:
what we actually want to know is, if a shared library is available (and then we prefer it).
Before that, we assumed that either a shared or a static library exists, which still works but it somewhat obfuscating.
> CMake: HDF5 Has Shared

- src/include/splash/Selection.hpp
- src/include/splash/domains/Domain.hpp
- src/include/splash/domains/DomainData.hpp
This commit fixes warnings in public header files caused by libSplash in external projects (as in [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu/issues/1042)) when compiled with `-Wshadow`.
Since the affected classes are used as structs (purely public members) refining those in a `member_m` naming scheme would be more intrusive then changing the naming in their contructors.
Generally it is pretty annoying that `-Wshadow` also calls out contructors but keeping those clean allows to find more serious bugs with it.
Related to #190 but does not yet fix the Splash compile itself (non-public headers and implementations).
> Fix Public Wshadow Warnings

- src/include/splash/basetypes/ColTypeBool.hpp
- src/include/splash/version.hpp
- tests/readBoolChar.py
Else it does not identify those as `bool_` but as `int8`.
Regression for #153 (still in `dev`).
`h5py` representation since #153 (example for a `False` value):
```
scalar attribute: (1, <type 'numpy.int8'>)
data set: <HDF5 dataset "data_bool": shape (7, 7, 7), type "|i1">,
<class 'h5py._hl.dataset.Dataset'>,
dtype([(({'vals': {'true': 1, 'false': 0}}, 'enum'), 'i1')])
```
and now (same enum but with different label):
```
scalar attribute: False, <type 'numpy.bool_'>
data set: <HDF5 dataset "data_bool": shape (7, 7, 7), type "|b1">,
<class 'h5py._hl.dataset.Dataset'>,
dtype('bool')
```
Increases format by a minor since the structure is still the same but the identification in `h5py` is improved (and it is still not in a stable release).
> Bool: CAPS Enum Labels for h5py

- src/ParallelDataCollector.cpp
- src/SDCHelper.cpp
- src/SerialDataCollector.cpp
Close #184 by using the new `h5py` compatible bool type for our `/header/compression` attribute.
Increases the format by a minor - can be merged directly **after** #198 (purely informative argument that has no influence on transparent reads of compressed or uncompressed data sets; since last stable release already a major format increase).
Also changes internally to use our `ColTypeInt32` instead of the native type for `SDC_ATTR_MAX_ID` which is not changing the format since they are identical (or at least `H5T_NATIVE_INT32` ([ANSI C9x](https://www.hdfgroup.org/HDF5/doc/RM/PredefDTypes.html)) and [H5T_INTEL_I32](https://github.com/ax3l/libSplash/blob/018f7c493e543cd040d5613ed0709ab81ddebfc6/src/include/splash/basetypes/basetypes_atomic.hpp#L57) seem to be identical).
`h5diff` output: …
> Close #184 Compression Header as Bool

- src/include/splash/DataCollector.hpp
- src/include/splash/sdc_defines.hpp
Close #157 Use the term `iteration` instead of (time) `step` also in last doxygen strings that were missing.
Removes also an unused define.
> Close #157 Iteration in Doxygen

- CHANGELOG.md
- src/include/splash/version.hpp
Adds the change log and version increase for the **release 1.3.0** of `libSplash`.
> Release 1.3.0: Add Changelog

- INSTALL.md
Removes the "parallel libSplash is beta status" note since it is stable and adds some links to interface documentations.
> INSTALL.md: Remove "beta" notice for PHDF5

- INSTALL.md
- examples/CMakeLists.txt
- examples/parallel_domain_write/parallel_domain_write.cpp
Adds an example using the `ParallelDataCollector`.
Tries to be as close as possible to the "serial" (multiple POSIX files from MPI ranks) example of `mpi_domain_write`.
> Close #14 Add PDC Example

- src/include/splash/DataCollector.hpp
- src/include/splash/Dimensions.hpp
Removes two `_` prefixes for include guards.
This is generally discouraged and reserved,
https://gcc.gnu.org/onlinedocs/gcc-3.0.1/cpp_3.html#SEC23
found via a [flint++](https://github.com/L2Program/FlintPlusPlus) warning.
> Include Guards: No _ Prefix

- src/DomainCollector.cpp
- src/ParallelDataCollector.cpp
- src/ParallelDomainCollector.cpp
- src/SDCHelper.cpp
- src/SerialDataCollector.cpp
- tools/splashtools.cpp
C++ catch parameters should be passed by const reference.
This PR was not triggered by an immediate problem but should be fixed since it usually causes problems (e.g., boost program options usually segfaults when catched wrong). Found via [flint++](https://github.com/L2Program/FlintPlusPlus) checking.
References:
- http://en.cppreference.com/w/cpp/language/try_catch
> Catch By Reference

- src/ParallelDataCollector.cpp
- src/SerialDataCollector.cpp
- src/include/splash/basetypes/ColTypeBool.hpp
- tests/Parallel_SimpleDataTest.cpp
- tests/SimpleDataTest.cpp
- tests/include/Parallel_SimpleDataTest.h
Fixes #224 by implementing the `readMeta` members in `[Serial|Parallel]DataCollector` correctly in case more then one `entry` (data set) is available per iteration.
Implements:
- read meta data tests that check the `CollectionType` (serial, parallel)
Fixes
- `ColTypeBool` detection (was detected as `Unknown` due to a representation change in the last release)
- `readMeta` return type (returned first found `entry` before)
> Fix #224 `readMeta` ColType Detection

- CHANGELOG.md
- src/include/splash/version.hpp
Change log for the `1.3.1` bug fix release.
Increases the version number to `1.3.1`, file format unchanged.
> ChangeLog for Release 1.3.1

- CHANGELOG.md
- src/DCGroup.cpp
- src/include/splash/sdc_defines.hpp
- src/include/splash/version.hpp
- tests/readBoolChar.py
Close #219 by letting the `SerialDataCollector` write to `/` by default, too.
Follow-up to the change in `1.3.0` for the PDC (see #173).
Needed by several users to fulfill the `openPMD` standard with **serial** files where they actually want to write to pathes starting from `/`.
This PR already contains a change log since this will be the only change from the todays `1.3.1` release to go to `1.4.0`.  Reading old files needs manual tuning for global attributes: API increased to `1.4.0` and file format bumped to `4.0` since the changes in SDC are not backwards compatible without chaning the interpretation of the `write/readGlobalAttribute` API calls.
CC-ing @PrometheusPi (I will update PIConGPU requirements in the next days)
> Close #219 SDC GlobalAttibute Path to "/"

- CHANGELOG.md
- src/DCGroup.cpp
- src/include/splash/sdc_defines.hpp
- src/include/splash/version.hpp
- tests/readBoolChar.py
Lets the `SerialDataCollector` write *global* attributes to `/` by default, too.
Follow-up to the change in `libSplash 1.3.0` for the PDC (see #173).
Interface change for `SerialDataCollector` (SDC): reading old files needs manual tuning for global attributes:
- API increased to `1.4.0` and file format bumped to `4.0` since the changes in SDC are not backwards compatible.
> Release 1.4.0: SDC Global Attibute Path to "/"

- src/HandleMgr.cpp
- src/ParallelDataCollector.cpp
- src/SerialDataCollector.cpp
- src/include/splash/ParallelDataCollector.hpp
- src/include/splash/SerialDataCollector.hpp
- src/include/splash/core/DCHelper.hpp
- src/include/splash/core/HandleMgr.hpp
- tests/CMakeLists.txt
- tests/FilenameTest.cpp
- tests/Parallel_FilenameTest.cpp
- tests/Parallel_SerialDCTest.cpp
- tests/run_parallel_tests
- tests/run_tests
Allows passing full name to `SerialDataCollector`
Previously the `SerialDataCollector` created names like "foo.h5_0_0_0.h5" , this is now kept as "foo.h5"
For this it also changes the HandleMgr and extends its filename scheme by `FNS_FULLNAME` where the name is kept unchanged. Additionally checks where added for catching erroneously passing a full name into the DataCollectors when a base name was expected.
@ax3l
> Make filename creation consistent

- .travis.yml
- src/include/splash/basetypes/generateCollectionType.hpp
The function returns `ColTypeUnknown` on not-found.
Also the typeid check is superfluous as the static function `genType` of that type should per definition return an instance of itself. An assertion is added instead.
In case new `genType`'s are implemented, this will guarantee that no mem-leaks can occur.
> Fix comparison and docu of generateCollectionType

- CMakeLists.txt
- src/generateCollectionType.cpp
- src/include/splash/basetypes/generateCollectionType.hpp
This just moves the implementation into a cpp file.
Avoids duplicate definition issues and decreases compiletime.
> Implement generateCollectionType in cpp

- src/ParallelDataCollector.cpp
- src/include/splash/ParallelDataCollector.hpp
- src/include/splash/basetypes/ColTypeDimArray.hpp
This adds exception throwing for the invalid methods of ParallelDC.
I just run into an issue accidentally using one of them, which is pretty annoying.
> Throw exception on invalid calls

- src/ParallelDataCollector.cpp
- src/SerialDataCollector.cpp
- src/include/splash/DataCollector.hpp
- src/include/splash/core/DCGroup.hpp
- tests/AttributesTest.cpp
- tests/Parallel_AttributesTest.cpp
close #231 Attribute Writing: Create Group if Missing 
extent attribute test case (paralllel/serial) 
- write attribute to a not existing group
- validate written attribute
extent `writeAttribute()`  (paralllel/serial) 
- check if dataset/group exists
- create group if not exists
> Topic attributes for not existing groups

- .travis.yml
- CMakeLists.txt
The `-Werror` flag should not be shipped to users. We will enforce it manually for travis-ci testing so the (limited) set of compilers we test stays warning-free.
Nevertheless, a (new) warning on a system or compiler we did not test is not necessarily fatal and would be a showstopper for new users.
> Werror: On Travis Only

- CHANGELOG.md
- src/include/splash/version.hpp
Adds the change log and bumps the version for release `1.5.0`.
This release mainly fixes non-consistent APIs to increase usebility, such as serial file naming, attribute writing and throwing on wrong usage.
The file format is unchanged.
> ChangeLog for Release 1.5.0

- src/include/splash/core/DCHelper.hpp
Fix #255: The `size_t` math used for optimizing the chunk-size will flip to positive values on underflow automatically, making the `abs` that causes problems on GCC 6.2 unnecessary.
> Fix #255 DCHelper: Remove abs in size_t math

- CHANGELOG.md
- src/include/splash/version.hpp
`SerialDataCollector` file name interface change #242: this feature was accidentally not included in the `1.5.0` release.
Also, [git revert](http://stackoverflow.com/questions/40285123/git-release-with-a-reverted-commit-on-master) is a tricky beast.
> Release 1.6.0: Changelog

- CMakeLists.txt
- src/AttributeInfo.cpp
- src/DCAttribute.cpp
- src/DCAttributeInfo.cpp
- src/DomainCollector.cpp
- src/ParallelDataCollector.cpp
- src/ParallelDomainCollector.cpp
- src/SerialDataCollector.cpp
- src/include/splash/AttributeInfo.hpp
- src/include/splash/DCAttributeInfo.hpp
- src/include/splash/DCException.hpp
- src/include/splash/DataCollector.hpp
- src/include/splash/IParallelDataCollector.hpp
- src/include/splash/ParallelDataCollector.hpp
- src/include/splash/SerialDataCollector.hpp
- src/include/splash/core/DCAttribute.hpp
- src/include/splash/core/H5IdWrapper.hpp
- src/include/splash/core/splashMacros.hpp
- src/include/splash/splash_parallel.h
- src/include/splash/splash_serial.h
- tests/AttributesTest.cpp
- tests/CMakeLists.txt
- tests/Parallel_AttributesTest.cpp
- tests/include/AttributesTest.h
- tests/include/Parallel_AttributesTest.h
This adds methods for getting the attribute meta info. Possible usage would be:
``` C++
template<typename T>
void ReadAttribute(DataCollector& dc, T& attribute){
AttributeInfo info = dc.readAttributeInfo(42, NULL, "fooAttr");
// Check dimensionality
assert(info.IsScalar());
// Assume a trait GetCollectionType that returns the collection type from a
// given type such as int->ColTypeInt
// Deprecated functionality for fast transition (potentially unsafe)
assert(typeid(info.getType()) == typeid(typename GetCollectionType<T>::type));
assert(sizeof(attribute) == info.getMemSize());
info.read(&attribute, sizeof(attribute));
// OR:
// Cast data to given type. Note: This is the type of each data point. Attribute could still contain
// an nD array of data. Each of those points may be converted …
```
> Attribute meta info

- src/include/splash/CollectionType.hpp
- src/include/splash/Dimensions.hpp
- src/include/splash/basetypes/ColTypeDim.hpp
- src/include/splash/basetypes/ColTypeDimArray.hpp
- src/include/splash/basetypes/ColTypeString.hpp
Found this branch that is still not in any PR.
This keeps the actual collection type for strings and removes some entanglements of ColTypeDim with Dimensions.
The former is the most important part as it allows meaningful `isNullTerminated` and `isVariableLength` queries. Without keeping the original H5 types this would return the wrong results.
> Keep info on H5 datatypes in collection types

- src/include/splash/domains/DataContainer.hpp
- tests/DomainsTest.cpp
Proposed fix for #254 on which the offset >0 during reads could never be determined.
@Flamefire maybe you want to take a look? I would still like to add a test for that, but did not dig deeper.
> DataContainer: Fix Offset Read

- src/include/splash/core/H5IdWrapper.hpp
- src/include/splash/core/splashMacros.hpp
Fix warning of an unused, local, static variable that is not mutable in compilers with the usual methods (since it is static).
Close #265
> Warning: Fix Unused

- CHANGELOG.md
- README.md
- src/include/splash/version.hpp
Release 1.7.0
-------------
**Date:** 2018-01-22
This release adds modernized CMake scripts including CMake config packages on install with targets. A new `readAttributeInfo` method was added to the `DataCollector` for save reading of types and extents of attributes. On reads, the `offset` in `DataContainer` for non-zero offsets in domains was fixed. Due to a bug in upsteam CMake, at least version 3.10.0 of CMake is required now.
**Interface Changes**
- new read method: attribute meta info #248 #268
- keep info on H5 datatypes in collection types #259
**Bug Fixes**
- `DataContainer`: fix offset read #263
- `FindHDF5.cmake`: use upstream CMake version #267
**Misc**
- modern CMake3 scripts #269
- fix GitHub badges #254 #264
Thanks to @ax3l and @Flamefire for contributions to this release!
> Changelog & Version Bump: 1.7.0

- CMakeLists.txt
Fix #270: warning on install. The public header property is not needed here.
> CMake: Fix Install Warning

- INSTALL.md
Use the `CONFIG` mode in find_package to avoid mismatch with previous `FindSplash.cmake` MODULEs.
> CMake: find_package CONFIG
